spring.application.name=proy2

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
#para ver los sqls que se ejecutan
spring.jpa.show-sql=true 
#agregar user y pass
# spring.datasource.username=cumara
# spring.datasource.password=1234